# Generated by Django 2.2 on 2020-04-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('specification', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
