# Generated by Django 2.2 on 2020-04-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='phnum',
        ),
    ]
