# Generated by Django 2.2 on 2020-04-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_appoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoint',
            new_name='demo',
        ),
    ]
