# Generated by Django 2.2 on 2020-05-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_auto_20200430_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='demo',
        ),
    ]
