# Generated by Django 2.2 on 2020-05-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_auto_20200430_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='sex',
        ),
    ]
